"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelsCreateRequestTranslationsToJSON = exports.ChannelsCreateRequestTranslationsFromJSONTyped = exports.ChannelsCreateRequestTranslationsFromJSON = exports.instanceOfChannelsCreateRequestTranslations = void 0;
const ChannelsCreateRequestTranslationsEn_1 = require("./ChannelsCreateRequestTranslationsEn");
/**
 * Check if a given object implements the ChannelsCreateRequestTranslations interface.
 */
function instanceOfChannelsCreateRequestTranslations(value) {
    return true;
}
exports.instanceOfChannelsCreateRequestTranslations = instanceOfChannelsCreateRequestTranslations;
function ChannelsCreateRequestTranslationsFromJSON(json) {
    return ChannelsCreateRequestTranslationsFromJSONTyped(json, false);
}
exports.ChannelsCreateRequestTranslationsFromJSON = ChannelsCreateRequestTranslationsFromJSON;
function ChannelsCreateRequestTranslationsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'en': json['en'] == null ? undefined : (0, ChannelsCreateRequestTranslationsEn_1.ChannelsCreateRequestTranslationsEnFromJSON)(json['en']),
        'ru': json['ru'] == null ? undefined : (0, ChannelsCreateRequestTranslationsEn_1.ChannelsCreateRequestTranslationsEnFromJSON)(json['ru']),
    };
}
exports.ChannelsCreateRequestTranslationsFromJSONTyped = ChannelsCreateRequestTranslationsFromJSONTyped;
function ChannelsCreateRequestTranslationsToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'en': (0, ChannelsCreateRequestTranslationsEn_1.ChannelsCreateRequestTranslationsEnToJSON)(value['en']),
        'ru': (0, ChannelsCreateRequestTranslationsEn_1.ChannelsCreateRequestTranslationsEnToJSON)(value['ru']),
    };
}
exports.ChannelsCreateRequestTranslationsToJSON = ChannelsCreateRequestTranslationsToJSON;
