"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelsCreateRequestAvatarFileToJSON = exports.ChannelsCreateRequestAvatarFileFromJSONTyped = exports.ChannelsCreateRequestAvatarFileFromJSON = exports.instanceOfChannelsCreateRequestAvatarFile = void 0;
/**
 * Check if a given object implements the ChannelsCreateRequestAvatarFile interface.
 */
function instanceOfChannelsCreateRequestAvatarFile(value) {
    if (!('id' in value))
        return false;
    return true;
}
exports.instanceOfChannelsCreateRequestAvatarFile = instanceOfChannelsCreateRequestAvatarFile;
function ChannelsCreateRequestAvatarFileFromJSON(json) {
    return ChannelsCreateRequestAvatarFileFromJSONTyped(json, false);
}
exports.ChannelsCreateRequestAvatarFileFromJSON = ChannelsCreateRequestAvatarFileFromJSON;
function ChannelsCreateRequestAvatarFileFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
    };
}
exports.ChannelsCreateRequestAvatarFileFromJSONTyped = ChannelsCreateRequestAvatarFileFromJSONTyped;
function ChannelsCreateRequestAvatarFileToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
    };
}
exports.ChannelsCreateRequestAvatarFileToJSON = ChannelsCreateRequestAvatarFileToJSON;
