/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ChannelsCreateRequestAvatarFile } from './ChannelsCreateRequestAvatarFile';
/**
 *
 * @export
 * @interface ChannelsUpdateRequest
 */
export interface ChannelsUpdateRequest {
    /**
     *
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    description?: string;
    /**
     *
     * @type {ChannelsCreateRequestAvatarFile}
     * @memberof ChannelsUpdateRequest
     */
    avatarFile: ChannelsCreateRequestAvatarFile;
    /**
     *
     * @type {boolean}
     * @memberof ChannelsUpdateRequest
     */
    showCollectedSum: boolean;
}
/**
 * Check if a given object implements the ChannelsUpdateRequest interface.
 */
export declare function instanceOfChannelsUpdateRequest(value: object): boolean;
export declare function ChannelsUpdateRequestFromJSON(json: any): ChannelsUpdateRequest;
export declare function ChannelsUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsUpdateRequest;
export declare function ChannelsUpdateRequestToJSON(value?: ChannelsUpdateRequest | null): any;
