/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PublicChannel } from './PublicChannel';
/**
 *
 * @export
 * @interface ChannelsPublicIdGet200Response
 */
export interface ChannelsPublicIdGet200Response {
    /**
     *
     * @type {string}
     * @memberof ChannelsPublicIdGet200Response
     */
    status: string;
    /**
     *
     * @type {PublicChannel}
     * @memberof ChannelsPublicIdGet200Response
     */
    data: PublicChannel;
}
/**
 * Check if a given object implements the ChannelsPublicIdGet200Response interface.
 */
export declare function instanceOfChannelsPublicIdGet200Response(value: object): boolean;
export declare function ChannelsPublicIdGet200ResponseFromJSON(json: any): ChannelsPublicIdGet200Response;
export declare function ChannelsPublicIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsPublicIdGet200Response;
export declare function ChannelsPublicIdGet200ResponseToJSON(value?: ChannelsPublicIdGet200Response | null): any;
