"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelsPublicIdGet200ResponseToJSON = exports.ChannelsPublicIdGet200ResponseFromJSONTyped = exports.ChannelsPublicIdGet200ResponseFromJSON = exports.instanceOfChannelsPublicIdGet200Response = void 0;
const PublicChannel_1 = require("./PublicChannel");
/**
 * Check if a given object implements the ChannelsPublicIdGet200Response interface.
 */
function instanceOfChannelsPublicIdGet200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfChannelsPublicIdGet200Response = instanceOfChannelsPublicIdGet200Response;
function ChannelsPublicIdGet200ResponseFromJSON(json) {
    return ChannelsPublicIdGet200ResponseFromJSONTyped(json, false);
}
exports.ChannelsPublicIdGet200ResponseFromJSON = ChannelsPublicIdGet200ResponseFromJSON;
function ChannelsPublicIdGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (0, PublicChannel_1.PublicChannelFromJSON)(json['data']),
    };
}
exports.ChannelsPublicIdGet200ResponseFromJSONTyped = ChannelsPublicIdGet200ResponseFromJSONTyped;
function ChannelsPublicIdGet200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (0, PublicChannel_1.PublicChannelToJSON)(value['data']),
    };
}
exports.ChannelsPublicIdGet200ResponseToJSON = ChannelsPublicIdGet200ResponseToJSON;
