"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelsCreate200ResponseToJSON = exports.ChannelsCreate200ResponseFromJSONTyped = exports.ChannelsCreate200ResponseFromJSON = exports.instanceOfChannelsCreate200Response = void 0;
const PrivateChannel_1 = require("./PrivateChannel");
/**
 * Check if a given object implements the ChannelsCreate200Response interface.
 */
function instanceOfChannelsCreate200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfChannelsCreate200Response = instanceOfChannelsCreate200Response;
function ChannelsCreate200ResponseFromJSON(json) {
    return ChannelsCreate200ResponseFromJSONTyped(json, false);
}
exports.ChannelsCreate200ResponseFromJSON = ChannelsCreate200ResponseFromJSON;
function ChannelsCreate200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (0, PrivateChannel_1.PrivateChannelFromJSON)(json['data']),
    };
}
exports.ChannelsCreate200ResponseFromJSONTyped = ChannelsCreate200ResponseFromJSONTyped;
function ChannelsCreate200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (0, PrivateChannel_1.PrivateChannelToJSON)(value['data']),
    };
}
exports.ChannelsCreate200ResponseToJSON = ChannelsCreate200ResponseToJSON;
