/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PublicChannel } from './PublicChannel';
/**
 *
 * @export
 * @interface ChannelsFeaturedList200Response
 */
export interface ChannelsFeaturedList200Response {
    /**
     *
     * @type {string}
     * @memberof ChannelsFeaturedList200Response
     */
    status: string;
    /**
     *
     * @type {Array<PublicChannel>}
     * @memberof ChannelsFeaturedList200Response
     */
    data: Array<PublicChannel>;
    /**
     *
     * @type {number}
     * @memberof ChannelsFeaturedList200Response
     */
    count: number;
    /**
     *
     * @type {number}
     * @memberof ChannelsFeaturedList200Response
     */
    total: number;
}
/**
 * Check if a given object implements the ChannelsFeaturedList200Response interface.
 */
export declare function instanceOfChannelsFeaturedList200Response(value: object): boolean;
export declare function ChannelsFeaturedList200ResponseFromJSON(json: any): ChannelsFeaturedList200Response;
export declare function ChannelsFeaturedList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsFeaturedList200Response;
export declare function ChannelsFeaturedList200ResponseToJSON(value?: ChannelsFeaturedList200Response | null): any;
