/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ChannelsCreateRequestTranslationsEn } from './ChannelsCreateRequestTranslationsEn';
/**
 *
 * @export
 * @interface ChannelsCreateRequestTranslations
 */
export interface ChannelsCreateRequestTranslations {
    /**
     *
     * @type {ChannelsCreateRequestTranslationsEn}
     * @memberof ChannelsCreateRequestTranslations
     */
    en?: ChannelsCreateRequestTranslationsEn;
    /**
     *
     * @type {ChannelsCreateRequestTranslationsEn}
     * @memberof ChannelsCreateRequestTranslations
     */
    ru?: ChannelsCreateRequestTranslationsEn;
}
/**
 * Check if a given object implements the ChannelsCreateRequestTranslations interface.
 */
export declare function instanceOfChannelsCreateRequestTranslations(value: object): boolean;
export declare function ChannelsCreateRequestTranslationsFromJSON(json: any): ChannelsCreateRequestTranslations;
export declare function ChannelsCreateRequestTranslationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsCreateRequestTranslations;
export declare function ChannelsCreateRequestTranslationsToJSON(value?: ChannelsCreateRequestTranslations | null): any;
