"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelsUpdateRequestToJSON = exports.ChannelsUpdateRequestFromJSONTyped = exports.ChannelsUpdateRequestFromJSON = exports.instanceOfChannelsUpdateRequest = void 0;
const UsersProfileUpdateRequestAvatar_1 = require("./UsersProfileUpdateRequestAvatar");
/**
 * Check if a given object implements the ChannelsUpdateRequest interface.
 */
function instanceOfChannelsUpdateRequest(value) {
    if (!('id' in value))
        return false;
    if (!('name' in value))
        return false;
    if (!('title' in value))
        return false;
    if (!('avatarFile' in value))
        return false;
    if (!('showCollectedSum' in value))
        return false;
    return true;
}
exports.instanceOfChannelsUpdateRequest = instanceOfChannelsUpdateRequest;
function ChannelsUpdateRequestFromJSON(json) {
    return ChannelsUpdateRequestFromJSONTyped(json, false);
}
exports.ChannelsUpdateRequestFromJSON = ChannelsUpdateRequestFromJSON;
function ChannelsUpdateRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'avatarFile': (0, UsersProfileUpdateRequestAvatar_1.UsersProfileUpdateRequestAvatarFromJSON)(json['avatar_file']),
        'showCollectedSum': json['show_collected_sum'],
    };
}
exports.ChannelsUpdateRequestFromJSONTyped = ChannelsUpdateRequestFromJSONTyped;
function ChannelsUpdateRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'avatar_file': (0, UsersProfileUpdateRequestAvatar_1.UsersProfileUpdateRequestAvatarToJSON)(value['avatarFile']),
        'show_collected_sum': value['showCollectedSum'],
    };
}
exports.ChannelsUpdateRequestToJSON = ChannelsUpdateRequestToJSON;
