"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelsOwnedList200ResponseToJSON = exports.ChannelsOwnedList200ResponseFromJSONTyped = exports.ChannelsOwnedList200ResponseFromJSON = exports.instanceOfChannelsOwnedList200Response = void 0;
const PrivateChannel_1 = require("./PrivateChannel");
/**
 * Check if a given object implements the ChannelsOwnedList200Response interface.
 */
function instanceOfChannelsOwnedList200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    if (!('count' in value))
        return false;
    if (!('total' in value))
        return false;
    return true;
}
exports.instanceOfChannelsOwnedList200Response = instanceOfChannelsOwnedList200Response;
function ChannelsOwnedList200ResponseFromJSON(json) {
    return ChannelsOwnedList200ResponseFromJSONTyped(json, false);
}
exports.ChannelsOwnedList200ResponseFromJSON = ChannelsOwnedList200ResponseFromJSON;
function ChannelsOwnedList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (json['data'].map(PrivateChannel_1.PrivateChannelFromJSON)),
        'count': json['count'],
        'total': json['total'],
    };
}
exports.ChannelsOwnedList200ResponseFromJSONTyped = ChannelsOwnedList200ResponseFromJSONTyped;
function ChannelsOwnedList200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (value['data'].map(PrivateChannel_1.PrivateChannelToJSON)),
        'count': value['count'],
        'total': value['total'],
    };
}
exports.ChannelsOwnedList200ResponseToJSON = ChannelsOwnedList200ResponseToJSON;
