/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ChannelsCreateRequestAvatarFile
 */
export interface ChannelsCreateRequestAvatarFile {
    /**
     *
     * @type {string}
     * @memberof ChannelsCreateRequestAvatarFile
     */
    id: string;
}
/**
 * Check if a given object implements the ChannelsCreateRequestAvatarFile interface.
 */
export declare function instanceOfChannelsCreateRequestAvatarFile(value: object): boolean;
export declare function ChannelsCreateRequestAvatarFileFromJSON(json: any): ChannelsCreateRequestAvatarFile;
export declare function ChannelsCreateRequestAvatarFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsCreateRequestAvatarFile;
export declare function ChannelsCreateRequestAvatarFileToJSON(value?: ChannelsCreateRequestAvatarFile | null): any;
