/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UsersProfileUpdateRequestAvatar } from './UsersProfileUpdateRequestAvatar';
/**
 *
 * @export
 * @interface ChannelsCreateRequest
 */
export interface ChannelsCreateRequest {
    /**
     *
     * @type {string}
     * @memberof ChannelsCreateRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ChannelsCreateRequest
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof ChannelsCreateRequest
     */
    description?: string;
    /**
     *
     * @type {UsersProfileUpdateRequestAvatar}
     * @memberof ChannelsCreateRequest
     */
    avatarFile: UsersProfileUpdateRequestAvatar;
    /**
     *
     * @type {boolean}
     * @memberof ChannelsCreateRequest
     */
    showCollectedSum?: boolean;
}
/**
 * Check if a given object implements the ChannelsCreateRequest interface.
 */
export declare function instanceOfChannelsCreateRequest(value: object): boolean;
export declare function ChannelsCreateRequestFromJSON(json: any): ChannelsCreateRequest;
export declare function ChannelsCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsCreateRequest;
export declare function ChannelsCreateRequestToJSON(value?: ChannelsCreateRequest | null): any;
