"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelsFeaturedList200ResponseToJSON = exports.ChannelsFeaturedList200ResponseFromJSONTyped = exports.ChannelsFeaturedList200ResponseFromJSON = exports.instanceOfChannelsFeaturedList200Response = void 0;
const PublicChannel_1 = require("./PublicChannel");
/**
 * Check if a given object implements the ChannelsFeaturedList200Response interface.
 */
function instanceOfChannelsFeaturedList200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    if (!('count' in value))
        return false;
    if (!('total' in value))
        return false;
    return true;
}
exports.instanceOfChannelsFeaturedList200Response = instanceOfChannelsFeaturedList200Response;
function ChannelsFeaturedList200ResponseFromJSON(json) {
    return ChannelsFeaturedList200ResponseFromJSONTyped(json, false);
}
exports.ChannelsFeaturedList200ResponseFromJSON = ChannelsFeaturedList200ResponseFromJSON;
function ChannelsFeaturedList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (json['data'].map(PublicChannel_1.PublicChannelFromJSON)),
        'count': json['count'],
        'total': json['total'],
    };
}
exports.ChannelsFeaturedList200ResponseFromJSONTyped = ChannelsFeaturedList200ResponseFromJSONTyped;
function ChannelsFeaturedList200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (value['data'].map(PublicChannel_1.PublicChannelToJSON)),
        'count': value['count'],
        'total': value['total'],
    };
}
exports.ChannelsFeaturedList200ResponseToJSON = ChannelsFeaturedList200ResponseToJSON;
