"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CityToJSON = exports.CityFromJSONTyped = exports.CityFromJSON = exports.instanceOfCity = void 0;
/**
 * Check if a given object implements the City interface.
 */
function instanceOfCity(value) {
    if (!('id' in value))
        return false;
    if (!('name' in value))
        return false;
    if (!('regionId' in value))
        return false;
    return true;
}
exports.instanceOfCity = instanceOfCity;
function CityFromJSON(json) {
    return CityFromJSONTyped(json, false);
}
exports.CityFromJSON = CityFromJSON;
function CityFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'regionId': json['region_id'],
    };
}
exports.CityFromJSONTyped = CityFromJSONTyped;
function CityToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'region_id': value['regionId'],
    };
}
exports.CityToJSON = CityToJSON;
