/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface City
 */
export interface City {
    /**
     *
     * @type {string}
     * @memberof City
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof City
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof City
     */
    regionId: string;
}
/**
 * Check if a given object implements the City interface.
 */
export declare function instanceOfCity(value: object): boolean;
export declare function CityFromJSON(json: any): City;
export declare function CityFromJSONTyped(json: any, ignoreDiscriminator: boolean): City;
export declare function CityToJSON(value?: City | null): any;
