/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Country
 */
export interface Country {
    /**
     *
     * @type {string}
     * @memberof Country
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Country
     */
    name: string;
}
/**
 * Check if a given object implements the Country interface.
 */
export declare function instanceOfCountry(value: object): boolean;
export declare function CountryFromJSON(json: any): Country;
export declare function CountryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Country;
export declare function CountryToJSON(value?: Country | null): any;
