"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DonationsInit200ResponseToJSON = exports.DonationsInit200ResponseFromJSONTyped = exports.DonationsInit200ResponseFromJSON = exports.instanceOfDonationsInit200Response = void 0;
const DonationsInit200ResponseData_1 = require("./DonationsInit200ResponseData");
/**
 * Check if a given object implements the DonationsInit200Response interface.
 */
function instanceOfDonationsInit200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfDonationsInit200Response = instanceOfDonationsInit200Response;
function DonationsInit200ResponseFromJSON(json) {
    return DonationsInit200ResponseFromJSONTyped(json, false);
}
exports.DonationsInit200ResponseFromJSON = DonationsInit200ResponseFromJSON;
function DonationsInit200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (0, DonationsInit200ResponseData_1.DonationsInit200ResponseDataFromJSON)(json['data']),
    };
}
exports.DonationsInit200ResponseFromJSONTyped = DonationsInit200ResponseFromJSONTyped;
function DonationsInit200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (0, DonationsInit200ResponseData_1.DonationsInit200ResponseDataToJSON)(value['data']),
    };
}
exports.DonationsInit200ResponseToJSON = DonationsInit200ResponseToJSON;
