"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DonationsStatus200ResponseToJSON = exports.DonationsStatus200ResponseFromJSONTyped = exports.DonationsStatus200ResponseFromJSON = exports.instanceOfDonationsStatus200Response = void 0;
const UsersEmailConfirmationResend200Response_1 = require("./UsersEmailConfirmationResend200Response");
/**
 * Check if a given object implements the DonationsStatus200Response interface.
 */
function instanceOfDonationsStatus200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfDonationsStatus200Response = instanceOfDonationsStatus200Response;
function DonationsStatus200ResponseFromJSON(json) {
    return DonationsStatus200ResponseFromJSONTyped(json, false);
}
exports.DonationsStatus200ResponseFromJSON = DonationsStatus200ResponseFromJSON;
function DonationsStatus200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (0, UsersEmailConfirmationResend200Response_1.UsersEmailConfirmationResend200ResponseFromJSON)(json['data']),
    };
}
exports.DonationsStatus200ResponseFromJSONTyped = DonationsStatus200ResponseFromJSONTyped;
function DonationsStatus200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (0, UsersEmailConfirmationResend200Response_1.UsersEmailConfirmationResend200ResponseToJSON)(value['data']),
    };
}
exports.DonationsStatus200ResponseToJSON = DonationsStatus200ResponseToJSON;
