"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DonationsStatusRequestToJSON = exports.DonationsStatusRequestFromJSONTyped = exports.DonationsStatusRequestFromJSON = exports.instanceOfDonationsStatusRequest = void 0;
/**
 * Check if a given object implements the DonationsStatusRequest interface.
 */
function instanceOfDonationsStatusRequest(value) {
    if (!('id' in value))
        return false;
    if (!('email' in value))
        return false;
    return true;
}
exports.instanceOfDonationsStatusRequest = instanceOfDonationsStatusRequest;
function DonationsStatusRequestFromJSON(json) {
    return DonationsStatusRequestFromJSONTyped(json, false);
}
exports.DonationsStatusRequestFromJSON = DonationsStatusRequestFromJSON;
function DonationsStatusRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'email': json['email'],
    };
}
exports.DonationsStatusRequestFromJSONTyped = DonationsStatusRequestFromJSONTyped;
function DonationsStatusRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'email': value['email'],
    };
}
exports.DonationsStatusRequestToJSON = DonationsStatusRequestToJSON;
