/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DonationsStatusRequest
 */
export interface DonationsStatusRequest {
    /**
     *
     * @type {string}
     * @memberof DonationsStatusRequest
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof DonationsStatusRequest
     */
    email: string;
}
/**
 * Check if a given object implements the DonationsStatusRequest interface.
 */
export declare function instanceOfDonationsStatusRequest(value: object): boolean;
export declare function DonationsStatusRequestFromJSON(json: any): DonationsStatusRequest;
export declare function DonationsStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationsStatusRequest;
export declare function DonationsStatusRequestToJSON(value?: DonationsStatusRequest | null): any;
