/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { DonationsInit200ResponseData } from './DonationsInit200ResponseData';
/**
 *
 * @export
 * @interface DonationsInit200Response
 */
export interface DonationsInit200Response {
    /**
     *
     * @type {string}
     * @memberof DonationsInit200Response
     */
    status: string;
    /**
     *
     * @type {DonationsInit200ResponseData}
     * @memberof DonationsInit200Response
     */
    data: DonationsInit200ResponseData;
}
/**
 * Check if a given object implements the DonationsInit200Response interface.
 */
export declare function instanceOfDonationsInit200Response(value: object): boolean;
export declare function DonationsInit200ResponseFromJSON(json: any): DonationsInit200Response;
export declare function DonationsInit200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationsInit200Response;
export declare function DonationsInit200ResponseToJSON(value?: DonationsInit200Response | null): any;
