"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DonationsInit200ResponseDataToJSON = exports.DonationsInit200ResponseDataFromJSONTyped = exports.DonationsInit200ResponseDataFromJSON = exports.instanceOfDonationsInit200ResponseData = void 0;
/**
 * Check if a given object implements the DonationsInit200ResponseData interface.
 */
function instanceOfDonationsInit200ResponseData(value) {
    if (!('type' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfDonationsInit200ResponseData = instanceOfDonationsInit200ResponseData;
function DonationsInit200ResponseDataFromJSON(json) {
    return DonationsInit200ResponseDataFromJSONTyped(json, false);
}
exports.DonationsInit200ResponseDataFromJSON = DonationsInit200ResponseDataFromJSON;
function DonationsInit200ResponseDataFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'type': json['type'],
        'data': json['data'],
    };
}
exports.DonationsInit200ResponseDataFromJSONTyped = DonationsInit200ResponseDataFromJSONTyped;
function DonationsInit200ResponseDataToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'type': value['type'],
        'data': value['data'],
    };
}
exports.DonationsInit200ResponseDataToJSON = DonationsInit200ResponseDataToJSON;
