"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DonationsInitRequestToJSON = exports.DonationsInitRequestFromJSONTyped = exports.DonationsInitRequestFromJSON = exports.instanceOfDonationsInitRequest = exports.DonationsInitRequestPaymentTypeEnum = void 0;
/**
 * @export
 */
exports.DonationsInitRequestPaymentTypeEnum = {
    RussiaCard: 'russia-card'
};
/**
 * Check if a given object implements the DonationsInitRequest interface.
 */
function instanceOfDonationsInitRequest(value) {
    if (!('channelId' in value))
        return false;
    if (!('sum' in value))
        return false;
    if (!('paymentType' in value))
        return false;
    return true;
}
exports.instanceOfDonationsInitRequest = instanceOfDonationsInitRequest;
function DonationsInitRequestFromJSON(json) {
    return DonationsInitRequestFromJSONTyped(json, false);
}
exports.DonationsInitRequestFromJSON = DonationsInitRequestFromJSON;
function DonationsInitRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'email': json['email'] == null ? undefined : json['email'],
        'channelId': json['channel_id'],
        'sum': json['sum'],
        'message': json['message'] == null ? undefined : json['message'],
        'paymentType': json['payment_type'],
    };
}
exports.DonationsInitRequestFromJSONTyped = DonationsInitRequestFromJSONTyped;
function DonationsInitRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'email': value['email'],
        'channel_id': value['channelId'],
        'sum': value['sum'],
        'message': value['message'],
        'payment_type': value['paymentType'],
    };
}
exports.DonationsInitRequestToJSON = DonationsInitRequestToJSON;
