/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UsersEmailConfirmationResend200Response } from './UsersEmailConfirmationResend200Response';
/**
 *
 * @export
 * @interface DonationsStatus200Response
 */
export interface DonationsStatus200Response {
    /**
     *
     * @type {string}
     * @memberof DonationsStatus200Response
     */
    status: string;
    /**
     *
     * @type {UsersEmailConfirmationResend200Response}
     * @memberof DonationsStatus200Response
     */
    data: UsersEmailConfirmationResend200Response;
}
/**
 * Check if a given object implements the DonationsStatus200Response interface.
 */
export declare function instanceOfDonationsStatus200Response(value: object): boolean;
export declare function DonationsStatus200ResponseFromJSON(json: any): DonationsStatus200Response;
export declare function DonationsStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationsStatus200Response;
export declare function DonationsStatus200ResponseToJSON(value?: DonationsStatus200Response | null): any;
