"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GeoToJSON = exports.GeoFromJSONTyped = exports.GeoFromJSON = exports.instanceOfGeo = void 0;
const City_1 = require("./City");
const Country_1 = require("./Country");
const Region_1 = require("./Region");
/**
 * Check if a given object implements the Geo interface.
 */
function instanceOfGeo(value) {
    if (!('city' in value))
        return false;
    if (!('region' in value))
        return false;
    if (!('country' in value))
        return false;
    return true;
}
exports.instanceOfGeo = instanceOfGeo;
function GeoFromJSON(json) {
    return GeoFromJSONTyped(json, false);
}
exports.GeoFromJSON = GeoFromJSON;
function GeoFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'city': (0, City_1.CityFromJSON)(json['city']),
        'region': (0, Region_1.RegionFromJSON)(json['region']),
        'country': (0, Country_1.CountryFromJSON)(json['country']),
    };
}
exports.GeoFromJSONTyped = GeoFromJSONTyped;
function GeoToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'city': (0, City_1.CityToJSON)(value['city']),
        'region': (0, Region_1.RegionToJSON)(value['region']),
        'country': (0, Country_1.CountryToJSON)(value['country']),
    };
}
exports.GeoToJSON = GeoToJSON;
