/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Geo } from './Geo';
/**
 *
 * @export
 * @interface GeoList200Response
 */
export interface GeoList200Response {
    /**
     *
     * @type {string}
     * @memberof GeoList200Response
     */
    status: string;
    /**
     *
     * @type {Array<Geo>}
     * @memberof GeoList200Response
     */
    data: Array<Geo>;
}
/**
 * Check if a given object implements the GeoList200Response interface.
 */
export declare function instanceOfGeoList200Response(value: object): boolean;
export declare function GeoList200ResponseFromJSON(json: any): GeoList200Response;
export declare function GeoList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoList200Response;
export declare function GeoList200ResponseToJSON(value?: GeoList200Response | null): any;
