"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GeoList200ResponseToJSON = exports.GeoList200ResponseFromJSONTyped = exports.GeoList200ResponseFromJSON = exports.instanceOfGeoList200Response = void 0;
const Geo_1 = require("./Geo");
/**
 * Check if a given object implements the GeoList200Response interface.
 */
function instanceOfGeoList200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfGeoList200Response = instanceOfGeoList200Response;
function GeoList200ResponseFromJSON(json) {
    return GeoList200ResponseFromJSONTyped(json, false);
}
exports.GeoList200ResponseFromJSON = GeoList200ResponseFromJSON;
function GeoList200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (json['data'].map(Geo_1.GeoFromJSON)),
    };
}
exports.GeoList200ResponseFromJSONTyped = GeoList200ResponseFromJSONTyped;
function GeoList200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (value['data'].map(Geo_1.GeoToJSON)),
    };
}
exports.GeoList200ResponseToJSON = GeoList200ResponseToJSON;
