/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     *
     * @type {string}
     * @memberof ModelError
     */
    status: ModelErrorStatusEnum;
    /**
     *
     * @type {string}
     * @memberof ModelError
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof ModelError
     */
    type?: string;
}
/**
 * @export
 */
export declare const ModelErrorStatusEnum: {
    readonly Error: "error";
};
export type ModelErrorStatusEnum = typeof ModelErrorStatusEnum[keyof typeof ModelErrorStatusEnum];
/**
 * Check if a given object implements the ModelError interface.
 */
export declare function instanceOfModelError(value: object): boolean;
export declare function ModelErrorFromJSON(json: any): ModelError;
export declare function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError;
export declare function ModelErrorToJSON(value?: ModelError | null): any;
