"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrivateFileToJSON = exports.PrivateFileFromJSONTyped = exports.PrivateFileFromJSON = exports.instanceOfPrivateFile = void 0;
/**
 * Check if a given object implements the PrivateFile interface.
 */
function instanceOfPrivateFile(value) {
    if (!('id' in value))
        return false;
    if (!('name' in value))
        return false;
    if (!('size' in value))
        return false;
    return true;
}
exports.instanceOfPrivateFile = instanceOfPrivateFile;
function PrivateFileFromJSON(json) {
    return PrivateFileFromJSONTyped(json, false);
}
exports.PrivateFileFromJSON = PrivateFileFromJSON;
function PrivateFileFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'size': json['size'],
        'externalHref': json['external_href'] == null ? undefined : json['external_href'],
    };
}
exports.PrivateFileFromJSONTyped = PrivateFileFromJSONTyped;
function PrivateFileToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'size': value['size'],
        'external_href': value['externalHref'],
    };
}
exports.PrivateFileToJSON = PrivateFileToJSON;
