/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PublicFile } from './PublicFile';
/**
 *
 * @export
 * @interface PrivateChannel
 */
export interface PrivateChannel {
    /**
     *
     * @type {boolean}
     * @memberof PrivateChannel
     */
    showCollectedSum: boolean;
    /**
     *
     * @type {string}
     * @memberof PrivateChannel
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof PrivateChannel
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof PrivateChannel
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof PrivateChannel
     */
    description?: string;
    /**
     *
     * @type {PublicFile}
     * @memberof PrivateChannel
     */
    avatarFile: PublicFile;
    /**
     *
     * @type {string}
     * @memberof PrivateChannel
     */
    creationDate: string;
}
/**
 * Check if a given object implements the PrivateChannel interface.
 */
export declare function instanceOfPrivateChannel(value: object): boolean;
export declare function PrivateChannelFromJSON(json: any): PrivateChannel;
export declare function PrivateChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateChannel;
export declare function PrivateChannelToJSON(value?: PrivateChannel | null): any;
