"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrivateChannelToJSON = exports.PrivateChannelFromJSONTyped = exports.PrivateChannelFromJSON = exports.instanceOfPrivateChannel = void 0;
const PrivateFile_1 = require("./PrivateFile");
/**
 * Check if a given object implements the PrivateChannel interface.
 */
function instanceOfPrivateChannel(value) {
    if (!('showCollectedSum' in value))
        return false;
    if (!('avatarFile' in value))
        return false;
    if (!('id' in value))
        return false;
    if (!('name' in value))
        return false;
    if (!('title' in value))
        return false;
    if (!('creationDate' in value))
        return false;
    return true;
}
exports.instanceOfPrivateChannel = instanceOfPrivateChannel;
function PrivateChannelFromJSON(json) {
    return PrivateChannelFromJSONTyped(json, false);
}
exports.PrivateChannelFromJSON = PrivateChannelFromJSON;
function PrivateChannelFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'showCollectedSum': json['show_collected_sum'],
        'avatarFile': (0, PrivateFile_1.PrivateFileFromJSON)(json['avatar_file']),
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'creationDate': json['creation_date'],
    };
}
exports.PrivateChannelFromJSONTyped = PrivateChannelFromJSONTyped;
function PrivateChannelToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'show_collected_sum': value['showCollectedSum'],
        'avatar_file': (0, PrivateFile_1.PrivateFileToJSON)(value['avatarFile']),
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'creation_date': value['creationDate'],
    };
}
exports.PrivateChannelToJSON = PrivateChannelToJSON;
