/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PrivateFile
 */
export interface PrivateFile {
    /**
     *
     * @type {string}
     * @memberof PrivateFile
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof PrivateFile
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof PrivateFile
     */
    size: number;
    /**
     *
     * @type {string}
     * @memberof PrivateFile
     */
    externalHref?: string;
}
/**
 * Check if a given object implements the PrivateFile interface.
 */
export declare function instanceOfPrivateFile(value: object): boolean;
export declare function PrivateFileFromJSON(json: any): PrivateFile;
export declare function PrivateFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateFile;
export declare function PrivateFileToJSON(value?: PrivateFile | null): any;
