/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { PublicFile } from './PublicFile';
/**
 *
 * @export
 * @interface PublicChannel
 */
export interface PublicChannel {
    /**
     *
     * @type {PublicFile}
     * @memberof PublicChannel
     */
    avatarFile: PublicFile;
    /**
     *
     * @type {string}
     * @memberof PublicChannel
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof PublicChannel
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof PublicChannel
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof PublicChannel
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof PublicChannel
     */
    creationDate: string;
    /**
     *
     * @type {boolean}
     * @memberof PublicChannel
     */
    showCollectedSum: boolean;
    /**
     *
     * @type {boolean}
     * @memberof PublicChannel
     */
    isOwned: boolean;
}
/**
 * Check if a given object implements the PublicChannel interface.
 */
export declare function instanceOfPublicChannel(value: object): boolean;
export declare function PublicChannelFromJSON(json: any): PublicChannel;
export declare function PublicChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicChannel;
export declare function PublicChannelToJSON(value?: PublicChannel | null): any;
