/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PublicFile
 */
export interface PublicFile {
    /**
     *
     * @type {string}
     * @memberof PublicFile
     */
    publicKey?: string;
    /**
     *
     * @type {string}
     * @memberof PublicFile
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof PublicFile
     */
    size: number;
    /**
     *
     * @type {string}
     * @memberof PublicFile
     */
    externalHref?: string;
}
/**
 * Check if a given object implements the PublicFile interface.
 */
export declare function instanceOfPublicFile(value: object): boolean;
export declare function PublicFileFromJSON(json: any): PublicFile;
export declare function PublicFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicFile;
export declare function PublicFileToJSON(value?: PublicFile | null): any;
