"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PublicFileToJSON = exports.PublicFileFromJSONTyped = exports.PublicFileFromJSON = exports.instanceOfPublicFile = void 0;
/**
 * Check if a given object implements the PublicFile interface.
 */
function instanceOfPublicFile(value) {
    if (!('name' in value))
        return false;
    if (!('size' in value))
        return false;
    return true;
}
exports.instanceOfPublicFile = instanceOfPublicFile;
function PublicFileFromJSON(json) {
    return PublicFileFromJSONTyped(json, false);
}
exports.PublicFileFromJSON = PublicFileFromJSON;
function PublicFileFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'publicKey': json['public_key'] == null ? undefined : json['public_key'],
        'name': json['name'],
        'size': json['size'],
        'externalHref': json['external_href'] == null ? undefined : json['external_href'],
    };
}
exports.PublicFileFromJSONTyped = PublicFileFromJSONTyped;
function PublicFileToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'public_key': value['publicKey'],
        'name': value['name'],
        'size': value['size'],
        'external_href': value['externalHref'],
    };
}
exports.PublicFileToJSON = PublicFileToJSON;
