"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PublicChannelToJSON = exports.PublicChannelFromJSONTyped = exports.PublicChannelFromJSON = exports.instanceOfPublicChannel = void 0;
const PublicFile_1 = require("./PublicFile");
/**
 * Check if a given object implements the PublicChannel interface.
 */
function instanceOfPublicChannel(value) {
    if (!('avatarFile' in value))
        return false;
    if (!('id' in value))
        return false;
    if (!('name' in value))
        return false;
    if (!('title' in value))
        return false;
    if (!('creationDate' in value))
        return false;
    if (!('showCollectedSum' in value))
        return false;
    if (!('isOwned' in value))
        return false;
    return true;
}
exports.instanceOfPublicChannel = instanceOfPublicChannel;
function PublicChannelFromJSON(json) {
    return PublicChannelFromJSONTyped(json, false);
}
exports.PublicChannelFromJSON = PublicChannelFromJSON;
function PublicChannelFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'avatarFile': (0, PublicFile_1.PublicFileFromJSON)(json['avatar_file']),
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'creationDate': json['creation_date'],
        'showCollectedSum': json['show_collected_sum'],
        'isOwned': json['is_owned'],
    };
}
exports.PublicChannelFromJSONTyped = PublicChannelFromJSONTyped;
function PublicChannelToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'avatar_file': (0, PublicFile_1.PublicFileToJSON)(value['avatarFile']),
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'creation_date': value['creationDate'],
        'show_collected_sum': value['showCollectedSum'],
        'is_owned': value['isOwned'],
    };
}
exports.PublicChannelToJSON = PublicChannelToJSON;
