"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegionToJSON = exports.RegionFromJSONTyped = exports.RegionFromJSON = exports.instanceOfRegion = void 0;
/**
 * Check if a given object implements the Region interface.
 */
function instanceOfRegion(value) {
    if (!('id' in value))
        return false;
    if (!('name' in value))
        return false;
    if (!('countryId' in value))
        return false;
    return true;
}
exports.instanceOfRegion = instanceOfRegion;
function RegionFromJSON(json) {
    return RegionFromJSONTyped(json, false);
}
exports.RegionFromJSON = RegionFromJSON;
function RegionFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'countryId': json['country_id'],
    };
}
exports.RegionFromJSONTyped = RegionFromJSONTyped;
function RegionToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'country_id': value['countryId'],
    };
}
exports.RegionToJSON = RegionToJSON;
