/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Region
 */
export interface Region {
    /**
     *
     * @type {string}
     * @memberof Region
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Region
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Region
     */
    countryId: string;
}
/**
 * Check if a given object implements the Region interface.
 */
export declare function instanceOfRegion(value: object): boolean;
export declare function RegionFromJSON(json: any): Region;
export declare function RegionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Region;
export declare function RegionToJSON(value?: Region | null): any;
