/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Translation
 */
export interface Translation {
    /**
     *
     * @type {string}
     * @memberof Translation
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof Translation
     */
    description?: string;
}
/**
 * Check if a given object implements the Translation interface.
 */
export declare function instanceOfTranslation(value: object): boolean;
export declare function TranslationFromJSON(json: any): Translation;
export declare function TranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Translation;
export declare function TranslationToJSON(value?: Translation | null): any;
