/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Translation } from './Translation';
/**
 *
 * @export
 * @interface Translations
 */
export interface Translations {
    /**
     *
     * @type {Translation}
     * @memberof Translations
     */
    en: Translation;
    /**
     *
     * @type {Translation}
     * @memberof Translations
     */
    ru: Translation;
}
/**
 * Check if a given object implements the Translations interface.
 */
export declare function instanceOfTranslations(value: object): boolean;
export declare function TranslationsFromJSON(json: any): Translations;
export declare function TranslationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Translations;
export declare function TranslationsToJSON(value?: Translations | null): any;
