"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TranslationsToJSON = exports.TranslationsFromJSONTyped = exports.TranslationsFromJSON = exports.instanceOfTranslations = void 0;
const Translation_1 = require("./Translation");
/**
 * Check if a given object implements the Translations interface.
 */
function instanceOfTranslations(value) {
    return true;
}
exports.instanceOfTranslations = instanceOfTranslations;
function TranslationsFromJSON(json) {
    return TranslationsFromJSONTyped(json, false);
}
exports.TranslationsFromJSON = TranslationsFromJSON;
function TranslationsFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'en': json['en'] == null ? undefined : (0, Translation_1.TranslationFromJSON)(json['en']),
        'ru': json['ru'] == null ? undefined : (0, Translation_1.TranslationFromJSON)(json['ru']),
    };
}
exports.TranslationsFromJSONTyped = TranslationsFromJSONTyped;
function TranslationsToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'en': (0, Translation_1.TranslationToJSON)(value['en']),
        'ru': (0, Translation_1.TranslationToJSON)(value['ru']),
    };
}
exports.TranslationsToJSON = TranslationsToJSON;
