"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersProfileGet200ResponseToJSON = exports.UsersProfileGet200ResponseFromJSONTyped = exports.UsersProfileGet200ResponseFromJSON = exports.instanceOfUsersProfileGet200Response = void 0;
const User_1 = require("./User");
/**
 * Check if a given object implements the UsersProfileGet200Response interface.
 */
function instanceOfUsersProfileGet200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfUsersProfileGet200Response = instanceOfUsersProfileGet200Response;
function UsersProfileGet200ResponseFromJSON(json) {
    return UsersProfileGet200ResponseFromJSONTyped(json, false);
}
exports.UsersProfileGet200ResponseFromJSON = UsersProfileGet200ResponseFromJSON;
function UsersProfileGet200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (0, User_1.UserFromJSON)(json['data']),
    };
}
exports.UsersProfileGet200ResponseFromJSONTyped = UsersProfileGet200ResponseFromJSONTyped;
function UsersProfileGet200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (0, User_1.UserToJSON)(value['data']),
    };
}
exports.UsersProfileGet200ResponseToJSON = UsersProfileGet200ResponseToJSON;
