"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersRegister200ResponseDataToJSON = exports.UsersRegister200ResponseDataFromJSONTyped = exports.UsersRegister200ResponseDataFromJSON = exports.instanceOfUsersRegister200ResponseData = void 0;
/**
 * Check if a given object implements the UsersRegister200ResponseData interface.
 */
function instanceOfUsersRegister200ResponseData(value) {
    if (!('token' in value))
        return false;
    return true;
}
exports.instanceOfUsersRegister200ResponseData = instanceOfUsersRegister200ResponseData;
function UsersRegister200ResponseDataFromJSON(json) {
    return UsersRegister200ResponseDataFromJSONTyped(json, false);
}
exports.UsersRegister200ResponseDataFromJSON = UsersRegister200ResponseDataFromJSON;
function UsersRegister200ResponseDataFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'token': json['token'],
    };
}
exports.UsersRegister200ResponseDataFromJSONTyped = UsersRegister200ResponseDataFromJSONTyped;
function UsersRegister200ResponseDataToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'token': value['token'],
    };
}
exports.UsersRegister200ResponseDataToJSON = UsersRegister200ResponseDataToJSON;
