"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersProfileUpdateRequestAvatarToJSON = exports.UsersProfileUpdateRequestAvatarFromJSONTyped = exports.UsersProfileUpdateRequestAvatarFromJSON = exports.instanceOfUsersProfileUpdateRequestAvatar = void 0;
/**
 * Check if a given object implements the UsersProfileUpdateRequestAvatar interface.
 */
function instanceOfUsersProfileUpdateRequestAvatar(value) {
    if (!('id' in value))
        return false;
    return true;
}
exports.instanceOfUsersProfileUpdateRequestAvatar = instanceOfUsersProfileUpdateRequestAvatar;
function UsersProfileUpdateRequestAvatarFromJSON(json) {
    return UsersProfileUpdateRequestAvatarFromJSONTyped(json, false);
}
exports.UsersProfileUpdateRequestAvatarFromJSON = UsersProfileUpdateRequestAvatarFromJSON;
function UsersProfileUpdateRequestAvatarFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
    };
}
exports.UsersProfileUpdateRequestAvatarFromJSONTyped = UsersProfileUpdateRequestAvatarFromJSONTyped;
function UsersProfileUpdateRequestAvatarToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
    };
}
exports.UsersProfileUpdateRequestAvatarToJSON = UsersProfileUpdateRequestAvatarToJSON;
