"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersRegisterRequestToJSON = exports.UsersRegisterRequestFromJSONTyped = exports.UsersRegisterRequestFromJSON = exports.instanceOfUsersRegisterRequest = void 0;
/**
 * Check if a given object implements the UsersRegisterRequest interface.
 */
function instanceOfUsersRegisterRequest(value) {
    if (!('login' in value))
        return false;
    if (!('password' in value))
        return false;
    if (!('name' in value))
        return false;
    return true;
}
exports.instanceOfUsersRegisterRequest = instanceOfUsersRegisterRequest;
function UsersRegisterRequestFromJSON(json) {
    return UsersRegisterRequestFromJSONTyped(json, false);
}
exports.UsersRegisterRequestFromJSON = UsersRegisterRequestFromJSON;
function UsersRegisterRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'login': json['login'],
        'password': json['password'],
        'name': json['name'],
    };
}
exports.UsersRegisterRequestFromJSONTyped = UsersRegisterRequestFromJSONTyped;
function UsersRegisterRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'login': value['login'],
        'password': value['password'],
        'name': value['name'],
    };
}
exports.UsersRegisterRequestToJSON = UsersRegisterRequestToJSON;
