"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersProfileUpdateRequestToJSON = exports.UsersProfileUpdateRequestFromJSONTyped = exports.UsersProfileUpdateRequestFromJSON = exports.instanceOfUsersProfileUpdateRequest = void 0;
const UsersProfileUpdateRequestAuth_1 = require("./UsersProfileUpdateRequestAuth");
const UsersProfileUpdateRequestAvatar_1 = require("./UsersProfileUpdateRequestAvatar");
/**
 * Check if a given object implements the UsersProfileUpdateRequest interface.
 */
function instanceOfUsersProfileUpdateRequest(value) {
    return true;
}
exports.instanceOfUsersProfileUpdateRequest = instanceOfUsersProfileUpdateRequest;
function UsersProfileUpdateRequestFromJSON(json) {
    return UsersProfileUpdateRequestFromJSONTyped(json, false);
}
exports.UsersProfileUpdateRequestFromJSON = UsersProfileUpdateRequestFromJSON;
function UsersProfileUpdateRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'auth': json['auth'] == null ? undefined : (0, UsersProfileUpdateRequestAuth_1.UsersProfileUpdateRequestAuthFromJSON)(json['auth']),
        'avatar': json['avatar'] == null ? undefined : (0, UsersProfileUpdateRequestAvatar_1.UsersProfileUpdateRequestAvatarFromJSON)(json['avatar']),
    };
}
exports.UsersProfileUpdateRequestFromJSONTyped = UsersProfileUpdateRequestFromJSONTyped;
function UsersProfileUpdateRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'email': value['email'],
        'name': value['name'],
        'auth': (0, UsersProfileUpdateRequestAuth_1.UsersProfileUpdateRequestAuthToJSON)(value['auth']),
        'avatar': (0, UsersProfileUpdateRequestAvatar_1.UsersProfileUpdateRequestAvatarToJSON)(value['avatar']),
    };
}
exports.UsersProfileUpdateRequestToJSON = UsersProfileUpdateRequestToJSON;
