"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserToJSON = exports.UserFromJSONTyped = exports.UserFromJSON = exports.instanceOfUser = void 0;
const PublicFile_1 = require("./PublicFile");
/**
 * Check if a given object implements the User interface.
 */
function instanceOfUser(value) {
    if (!('email' in value))
        return false;
    if (!('isEmailConfirmed' in value))
        return false;
    if (!('registrationDate' in value))
        return false;
    if (!('isModerationApproved' in value))
        return false;
    if (!('id' in value))
        return false;
    if (!('avatar' in value))
        return false;
    return true;
}
exports.instanceOfUser = instanceOfUser;
function UserFromJSON(json) {
    return UserFromJSONTyped(json, false);
}
exports.UserFromJSON = UserFromJSON;
function UserFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'email': json['email'],
        'isEmailConfirmed': json['is_email_confirmed'],
        'registrationDate': json['registration_date'],
        'isModerationApproved': json['is_moderation_approved'],
        'id': json['id'],
        'avatar': (0, PublicFile_1.PublicFileFromJSON)(json['avatar']),
    };
}
exports.UserFromJSONTyped = UserFromJSONTyped;
function UserToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'email': value['email'],
        'is_email_confirmed': value['isEmailConfirmed'],
        'registration_date': value['registrationDate'],
        'is_moderation_approved': value['isModerationApproved'],
        'id': value['id'],
        'avatar': (0, PublicFile_1.PublicFileToJSON)(value['avatar']),
    };
}
exports.UserToJSON = UserToJSON;
