"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersEmailPasswordResetRequestToJSON = exports.UsersEmailPasswordResetRequestFromJSONTyped = exports.UsersEmailPasswordResetRequestFromJSON = exports.instanceOfUsersEmailPasswordResetRequest = void 0;
/**
 * Check if a given object implements the UsersEmailPasswordResetRequest interface.
 */
function instanceOfUsersEmailPasswordResetRequest(value) {
    if (!('email' in value))
        return false;
    return true;
}
exports.instanceOfUsersEmailPasswordResetRequest = instanceOfUsersEmailPasswordResetRequest;
function UsersEmailPasswordResetRequestFromJSON(json) {
    return UsersEmailPasswordResetRequestFromJSONTyped(json, false);
}
exports.UsersEmailPasswordResetRequestFromJSON = UsersEmailPasswordResetRequestFromJSON;
function UsersEmailPasswordResetRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'email': json['email'],
    };
}
exports.UsersEmailPasswordResetRequestFromJSONTyped = UsersEmailPasswordResetRequestFromJSONTyped;
function UsersEmailPasswordResetRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'email': value['email'],
    };
}
exports.UsersEmailPasswordResetRequestToJSON = UsersEmailPasswordResetRequestToJSON;
