"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersProfileUpdateRequestAuthToJSON = exports.UsersProfileUpdateRequestAuthFromJSONTyped = exports.UsersProfileUpdateRequestAuthFromJSON = exports.instanceOfUsersProfileUpdateRequestAuth = void 0;
/**
 * Check if a given object implements the UsersProfileUpdateRequestAuth interface.
 */
function instanceOfUsersProfileUpdateRequestAuth(value) {
    if (!('currentPassword' in value))
        return false;
    if (!('newPassword' in value))
        return false;
    return true;
}
exports.instanceOfUsersProfileUpdateRequestAuth = instanceOfUsersProfileUpdateRequestAuth;
function UsersProfileUpdateRequestAuthFromJSON(json) {
    return UsersProfileUpdateRequestAuthFromJSONTyped(json, false);
}
exports.UsersProfileUpdateRequestAuthFromJSON = UsersProfileUpdateRequestAuthFromJSON;
function UsersProfileUpdateRequestAuthFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
    };
}
exports.UsersProfileUpdateRequestAuthFromJSONTyped = UsersProfileUpdateRequestAuthFromJSONTyped;
function UsersProfileUpdateRequestAuthToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
    };
}
exports.UsersProfileUpdateRequestAuthToJSON = UsersProfileUpdateRequestAuthToJSON;
