"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersEmailPasswordResetUpdateRequestToJSON = exports.UsersEmailPasswordResetUpdateRequestFromJSONTyped = exports.UsersEmailPasswordResetUpdateRequestFromJSON = exports.instanceOfUsersEmailPasswordResetUpdateRequest = void 0;
/**
 * Check if a given object implements the UsersEmailPasswordResetUpdateRequest interface.
 */
function instanceOfUsersEmailPasswordResetUpdateRequest(value) {
    if (!('token' in value))
        return false;
    if (!('newPassword' in value))
        return false;
    return true;
}
exports.instanceOfUsersEmailPasswordResetUpdateRequest = instanceOfUsersEmailPasswordResetUpdateRequest;
function UsersEmailPasswordResetUpdateRequestFromJSON(json) {
    return UsersEmailPasswordResetUpdateRequestFromJSONTyped(json, false);
}
exports.UsersEmailPasswordResetUpdateRequestFromJSON = UsersEmailPasswordResetUpdateRequestFromJSON;
function UsersEmailPasswordResetUpdateRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'token': json['token'],
        'newPassword': json['new_password'],
    };
}
exports.UsersEmailPasswordResetUpdateRequestFromJSONTyped = UsersEmailPasswordResetUpdateRequestFromJSONTyped;
function UsersEmailPasswordResetUpdateRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'token': value['token'],
        'new_password': value['newPassword'],
    };
}
exports.UsersEmailPasswordResetUpdateRequestToJSON = UsersEmailPasswordResetUpdateRequestToJSON;
