/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { User } from './User';
/**
 *
 * @export
 * @interface UsersProfileGet200Response
 */
export interface UsersProfileGet200Response {
    /**
     *
     * @type {string}
     * @memberof UsersProfileGet200Response
     */
    status: string;
    /**
     *
     * @type {User}
     * @memberof UsersProfileGet200Response
     */
    data: User;
}
/**
 * Check if a given object implements the UsersProfileGet200Response interface.
 */
export declare function instanceOfUsersProfileGet200Response(value: object): boolean;
export declare function UsersProfileGet200ResponseFromJSON(json: any): UsersProfileGet200Response;
export declare function UsersProfileGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileGet200Response;
export declare function UsersProfileGet200ResponseToJSON(value?: UsersProfileGet200Response | null): any;
