/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UsersRegister200ResponseData } from './UsersRegister200ResponseData';
/**
 *
 * @export
 * @interface UsersRegister200Response
 */
export interface UsersRegister200Response {
    /**
     *
     * @type {string}
     * @memberof UsersRegister200Response
     */
    status: string;
    /**
     *
     * @type {UsersRegister200ResponseData}
     * @memberof UsersRegister200Response
     */
    data: UsersRegister200ResponseData;
}
/**
 * Check if a given object implements the UsersRegister200Response interface.
 */
export declare function instanceOfUsersRegister200Response(value: object): boolean;
export declare function UsersRegister200ResponseFromJSON(json: any): UsersRegister200Response;
export declare function UsersRegister200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersRegister200Response;
export declare function UsersRegister200ResponseToJSON(value?: UsersRegister200Response | null): any;
