"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersRegister200ResponseToJSON = exports.UsersRegister200ResponseFromJSONTyped = exports.UsersRegister200ResponseFromJSON = exports.instanceOfUsersRegister200Response = void 0;
const UsersRegister200ResponseData_1 = require("./UsersRegister200ResponseData");
/**
 * Check if a given object implements the UsersRegister200Response interface.
 */
function instanceOfUsersRegister200Response(value) {
    if (!('status' in value))
        return false;
    if (!('data' in value))
        return false;
    return true;
}
exports.instanceOfUsersRegister200Response = instanceOfUsersRegister200Response;
function UsersRegister200ResponseFromJSON(json) {
    return UsersRegister200ResponseFromJSONTyped(json, false);
}
exports.UsersRegister200ResponseFromJSON = UsersRegister200ResponseFromJSON;
function UsersRegister200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
        'data': (0, UsersRegister200ResponseData_1.UsersRegister200ResponseDataFromJSON)(json['data']),
    };
}
exports.UsersRegister200ResponseFromJSONTyped = UsersRegister200ResponseFromJSONTyped;
function UsersRegister200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
        'data': (0, UsersRegister200ResponseData_1.UsersRegister200ResponseDataToJSON)(value['data']),
    };
}
exports.UsersRegister200ResponseToJSON = UsersRegister200ResponseToJSON;
