/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersEmailPasswordResetRequest
 */
export interface UsersEmailPasswordResetRequest {
    /**
     *
     * @type {string}
     * @memberof UsersEmailPasswordResetRequest
     */
    email: string;
}
/**
 * Check if a given object implements the UsersEmailPasswordResetRequest interface.
 */
export declare function instanceOfUsersEmailPasswordResetRequest(value: object): boolean;
export declare function UsersEmailPasswordResetRequestFromJSON(json: any): UsersEmailPasswordResetRequest;
export declare function UsersEmailPasswordResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersEmailPasswordResetRequest;
export declare function UsersEmailPasswordResetRequestToJSON(value?: UsersEmailPasswordResetRequest | null): any;
