"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersLoginRequestToJSON = exports.UsersLoginRequestFromJSONTyped = exports.UsersLoginRequestFromJSON = exports.instanceOfUsersLoginRequest = void 0;
/**
 * Check if a given object implements the UsersLoginRequest interface.
 */
function instanceOfUsersLoginRequest(value) {
    if (!('login' in value))
        return false;
    if (!('password' in value))
        return false;
    return true;
}
exports.instanceOfUsersLoginRequest = instanceOfUsersLoginRequest;
function UsersLoginRequestFromJSON(json) {
    return UsersLoginRequestFromJSONTyped(json, false);
}
exports.UsersLoginRequestFromJSON = UsersLoginRequestFromJSON;
function UsersLoginRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'login': json['login'],
        'password': json['password'],
    };
}
exports.UsersLoginRequestFromJSONTyped = UsersLoginRequestFromJSONTyped;
function UsersLoginRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'login': value['login'],
        'password': value['password'],
    };
}
exports.UsersLoginRequestToJSON = UsersLoginRequestToJSON;
