/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersLoginRequest
 */
export interface UsersLoginRequest {
    /**
     *
     * @type {string}
     * @memberof UsersLoginRequest
     */
    login: string;
    /**
     *
     * @type {string}
     * @memberof UsersLoginRequest
     */
    password: string;
}
/**
 * Check if a given object implements the UsersLoginRequest interface.
 */
export declare function instanceOfUsersLoginRequest(value: object): boolean;
export declare function UsersLoginRequestFromJSON(json: any): UsersLoginRequest;
export declare function UsersLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLoginRequest;
export declare function UsersLoginRequestToJSON(value?: UsersLoginRequest | null): any;
