/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersProfileUpdateRequestAuth
 */
export interface UsersProfileUpdateRequestAuth {
    /**
     *
     * @type {string}
     * @memberof UsersProfileUpdateRequestAuth
     */
    currentPassword: string;
    /**
     *
     * @type {string}
     * @memberof UsersProfileUpdateRequestAuth
     */
    newPassword: string;
}
/**
 * Check if a given object implements the UsersProfileUpdateRequestAuth interface.
 */
export declare function instanceOfUsersProfileUpdateRequestAuth(value: object): boolean;
export declare function UsersProfileUpdateRequestAuthFromJSON(json: any): UsersProfileUpdateRequestAuth;
export declare function UsersProfileUpdateRequestAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileUpdateRequestAuth;
export declare function UsersProfileUpdateRequestAuthToJSON(value?: UsersProfileUpdateRequestAuth | null): any;
