"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UsersProfileUpdate200ResponseToJSON = exports.UsersProfileUpdate200ResponseFromJSONTyped = exports.UsersProfileUpdate200ResponseFromJSON = exports.instanceOfUsersProfileUpdate200Response = void 0;
/**
 * Check if a given object implements the UsersProfileUpdate200Response interface.
 */
function instanceOfUsersProfileUpdate200Response(value) {
    if (!('status' in value))
        return false;
    return true;
}
exports.instanceOfUsersProfileUpdate200Response = instanceOfUsersProfileUpdate200Response;
function UsersProfileUpdate200ResponseFromJSON(json) {
    return UsersProfileUpdate200ResponseFromJSONTyped(json, false);
}
exports.UsersProfileUpdate200ResponseFromJSON = UsersProfileUpdate200ResponseFromJSON;
function UsersProfileUpdate200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'status': json['status'],
    };
}
exports.UsersProfileUpdate200ResponseFromJSONTyped = UsersProfileUpdate200ResponseFromJSONTyped;
function UsersProfileUpdate200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        'status': value['status'],
    };
}
exports.UsersProfileUpdate200ResponseToJSON = UsersProfileUpdate200ResponseToJSON;
