/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersProfileUpdate200Response
 */
export interface UsersProfileUpdate200Response {
    /**
     *
     * @type {string}
     * @memberof UsersProfileUpdate200Response
     */
    status: string;
}
/**
 * Check if a given object implements the UsersProfileUpdate200Response interface.
 */
export declare function instanceOfUsersProfileUpdate200Response(value: object): boolean;
export declare function UsersProfileUpdate200ResponseFromJSON(json: any): UsersProfileUpdate200Response;
export declare function UsersProfileUpdate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileUpdate200Response;
export declare function UsersProfileUpdate200ResponseToJSON(value?: UsersProfileUpdate200Response | null): any;
