/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersRegisterRequest
 */
export interface UsersRegisterRequest {
    /**
     *
     * @type {string}
     * @memberof UsersRegisterRequest
     */
    login: string;
    /**
     *
     * @type {string}
     * @memberof UsersRegisterRequest
     */
    password: string;
}
/**
 * Check if a given object implements the UsersRegisterRequest interface.
 */
export declare function instanceOfUsersRegisterRequest(value: object): boolean;
export declare function UsersRegisterRequestFromJSON(json: any): UsersRegisterRequest;
export declare function UsersRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersRegisterRequest;
export declare function UsersRegisterRequestToJSON(value?: UsersRegisterRequest | null): any;
