/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UsersProfileUpdateRequestAuth } from './UsersProfileUpdateRequestAuth';
import type { UsersProfileUpdateRequestAvatar } from './UsersProfileUpdateRequestAvatar';
/**
 *
 * @export
 * @interface UsersProfileUpdateRequest
 */
export interface UsersProfileUpdateRequest {
    /**
     *
     * @type {string}
     * @memberof UsersProfileUpdateRequest
     */
    email?: string;
    /**
     *
     * @type {UsersProfileUpdateRequestAuth}
     * @memberof UsersProfileUpdateRequest
     */
    auth?: UsersProfileUpdateRequestAuth;
    /**
     *
     * @type {UsersProfileUpdateRequestAvatar}
     * @memberof UsersProfileUpdateRequest
     */
    avatar?: UsersProfileUpdateRequestAvatar;
}
/**
 * Check if a given object implements the UsersProfileUpdateRequest interface.
 */
export declare function instanceOfUsersProfileUpdateRequest(value: object): boolean;
export declare function UsersProfileUpdateRequestFromJSON(json: any): UsersProfileUpdateRequest;
export declare function UsersProfileUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileUpdateRequest;
export declare function UsersProfileUpdateRequestToJSON(value?: UsersProfileUpdateRequest | null): any;
