/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UsersEmailConfirmationResend200Response
 */
export interface UsersEmailConfirmationResend200Response {
    /**
     *
     * @type {string}
     * @memberof UsersEmailConfirmationResend200Response
     */
    status: string;
}
/**
 * Check if a given object implements the UsersEmailConfirmationResend200Response interface.
 */
export declare function instanceOfUsersEmailConfirmationResend200Response(value: object): boolean;
export declare function UsersEmailConfirmationResend200ResponseFromJSON(json: any): UsersEmailConfirmationResend200Response;
export declare function UsersEmailConfirmationResend200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersEmailConfirmationResend200Response;
export declare function UsersEmailConfirmationResend200ResponseToJSON(value?: UsersEmailConfirmationResend200Response | null): any;
