/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { ChannelsCreate200Response, ChannelsCreateRequest, ChannelsFeaturedList200Response, ChannelsOwnedList200Response, ChannelsPublicIdGet200Response, ChannelsUpdateRequest } from '../models/index';
export interface ChannelsCreateOperationRequest {
    channelsCreateRequest: ChannelsCreateRequest;
}
export interface ChannelsFeaturedListRequest {
    limit: number;
    offset: number;
}
export interface ChannelsOwnedGetRequest {
    id: string;
}
export interface ChannelsOwnedListRequest {
    limit: number;
    offset: number;
}
export interface ChannelsPublicIdGetRequest {
    id: string;
}
export interface ChannelsPublicNameGetRequest {
    name: string;
}
export interface ChannelsUpdateOperationRequest {
    channelsUpdateRequest: ChannelsUpdateRequest;
}
/**
 *
 */
export declare class ChannelsApi extends runtime.BaseAPI {
    /**
     */
    channelsCreateRaw(requestParameters: ChannelsCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsCreate200Response>>;
    /**
     */
    channelsCreate(requestParameters: ChannelsCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsCreate200Response>;
    /**
     */
    channelsFeaturedListRaw(requestParameters: ChannelsFeaturedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsFeaturedList200Response>>;
    /**
     */
    channelsFeaturedList(requestParameters: ChannelsFeaturedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsFeaturedList200Response>;
    /**
     */
    channelsOwnedGetRaw(requestParameters: ChannelsOwnedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsCreate200Response>>;
    /**
     */
    channelsOwnedGet(requestParameters: ChannelsOwnedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsCreate200Response>;
    /**
     */
    channelsOwnedListRaw(requestParameters: ChannelsOwnedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsOwnedList200Response>>;
    /**
     */
    channelsOwnedList(requestParameters: ChannelsOwnedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsOwnedList200Response>;
    /**
     */
    channelsPublicIdGetRaw(requestParameters: ChannelsPublicIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsPublicIdGet200Response>>;
    /**
     */
    channelsPublicIdGet(requestParameters: ChannelsPublicIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsPublicIdGet200Response>;
    /**
     */
    channelsPublicNameGetRaw(requestParameters: ChannelsPublicNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsPublicIdGet200Response>>;
    /**
     */
    channelsPublicNameGet(requestParameters: ChannelsPublicNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsPublicIdGet200Response>;
    /**
     */
    channelsUpdateRaw(requestParameters: ChannelsUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsCreate200Response>>;
    /**
     */
    channelsUpdate(requestParameters: ChannelsUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsCreate200Response>;
}
