/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { GeoList200Response } from '../models/index';
/**
 *
 */
export declare class GeoApi extends runtime.BaseAPI {
    /**
     */
    geoListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeoList200Response>>;
    /**
     */
    geoList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeoList200Response>;
}
