/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import type { UsersLoginRequest, UsersProfileGet200Response, UsersProfileUpdate200Response, UsersProfileUpdateRequest, UsersRegister200Response, UsersRegisterRequest } from '../models/index';
export interface UsersLoginOperationRequest {
    usersLoginRequest: UsersLoginRequest;
}
export interface UsersProfileUpdateOperationRequest {
    usersProfileUpdateRequest: UsersProfileUpdateRequest;
}
export interface UsersRegisterOperationRequest {
    usersRegisterRequest: UsersRegisterRequest;
}
/**
 *
 */
export declare class UsersApi extends runtime.BaseAPI {
    /**
     */
    usersEmailConfirmationResendRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersProfileUpdate200Response>>;
    /**
     */
    usersEmailConfirmationResend(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersProfileUpdate200Response>;
    /**
     */
    usersLoginRaw(requestParameters: UsersLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersRegister200Response>>;
    /**
     */
    usersLogin(requestParameters: UsersLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersRegister200Response>;
    /**
     */
    usersProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersProfileGet200Response>>;
    /**
     */
    usersProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersProfileGet200Response>;
    /**
     */
    usersProfileUpdateRaw(requestParameters: UsersProfileUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersProfileUpdate200Response>>;
    /**
     */
    usersProfileUpdate(requestParameters: UsersProfileUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersProfileUpdate200Response>;
    /**
     */
    usersRegisterRaw(requestParameters: UsersRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersRegister200Response>>;
    /**
     */
    usersRegister(requestParameters: UsersRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersRegister200Response>;
}
