/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GeoList200Response,
} from '../models/index';
import {
    GeoList200ResponseFromJSON,
    GeoList200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class GeoApi extends runtime.BaseAPI {

    /**
     */
    async geoListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeoList200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/geo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeoList200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async geoList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeoList200Response> {
        const response = await this.geoListRaw(initOverrides);
        return await response.value();
    }

}
