/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UsersEmailConfirmationResend200Response,
  UsersEmailPasswordResetRequest,
  UsersEmailPasswordResetUpdateRequest,
  UsersProfileGet200Response,
  UsersRegister200Response,
  UsersRegisterRequest,
} from '../models/index';
import {
    UsersEmailConfirmationResend200ResponseFromJSON,
    UsersEmailConfirmationResend200ResponseToJSON,
    UsersEmailPasswordResetRequestFromJSON,
    UsersEmailPasswordResetRequestToJSON,
    UsersEmailPasswordResetUpdateRequestFromJSON,
    UsersEmailPasswordResetUpdateRequestToJSON,
    UsersProfileGet200ResponseFromJSON,
    UsersProfileGet200ResponseToJSON,
    UsersRegister200ResponseFromJSON,
    UsersRegister200ResponseToJSON,
    UsersRegisterRequestFromJSON,
    UsersRegisterRequestToJSON,
} from '../models/index';

export interface UsersEmailPasswordResetOperationRequest {
    usersEmailPasswordResetRequest: UsersEmailPasswordResetRequest;
}

export interface UsersEmailPasswordResetUpdateOperationRequest {
    usersEmailPasswordResetUpdateRequest: UsersEmailPasswordResetUpdateRequest;
}

export interface UsersLoginRequest {
    usersRegisterRequest: UsersRegisterRequest;
}

export interface UsersRegisterOperationRequest {
    usersRegisterRequest: UsersRegisterRequest;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     */
    async usersEmailConfirmationResendRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersEmailConfirmationResend200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // Token authentication
        }

        const response = await this.request({
            path: `/api/v1/users/emails/confirmation/resend`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersEmailConfirmationResend200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async usersEmailConfirmationResend(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersEmailConfirmationResend200Response> {
        const response = await this.usersEmailConfirmationResendRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async usersEmailPasswordResetRaw(requestParameters: UsersEmailPasswordResetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersEmailConfirmationResend200Response>> {
        if (requestParameters['usersEmailPasswordResetRequest'] == null) {
            throw new runtime.RequiredError(
                'usersEmailPasswordResetRequest',
                'Required parameter "usersEmailPasswordResetRequest" was null or undefined when calling usersEmailPasswordReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/users/password/reset`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersEmailPasswordResetRequestToJSON(requestParameters['usersEmailPasswordResetRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersEmailConfirmationResend200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async usersEmailPasswordReset(requestParameters: UsersEmailPasswordResetOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersEmailConfirmationResend200Response> {
        const response = await this.usersEmailPasswordResetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersEmailPasswordResetUpdateRaw(requestParameters: UsersEmailPasswordResetUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersEmailConfirmationResend200Response>> {
        if (requestParameters['usersEmailPasswordResetUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'usersEmailPasswordResetUpdateRequest',
                'Required parameter "usersEmailPasswordResetUpdateRequest" was null or undefined when calling usersEmailPasswordResetUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/users/password/reset`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UsersEmailPasswordResetUpdateRequestToJSON(requestParameters['usersEmailPasswordResetUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersEmailConfirmationResend200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async usersEmailPasswordResetUpdate(requestParameters: UsersEmailPasswordResetUpdateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersEmailConfirmationResend200Response> {
        const response = await this.usersEmailPasswordResetUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersLoginRaw(requestParameters: UsersLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersRegister200Response>> {
        if (requestParameters['usersRegisterRequest'] == null) {
            throw new runtime.RequiredError(
                'usersRegisterRequest',
                'Required parameter "usersRegisterRequest" was null or undefined when calling usersLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersRegisterRequestToJSON(requestParameters['usersRegisterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersRegister200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async usersLogin(requestParameters: UsersLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersRegister200Response> {
        const response = await this.usersLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async usersProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersProfileGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Session-Token"] = await this.configuration.apiKey("X-Session-Token"); // Token authentication
        }

        const response = await this.request({
            path: `/api/v1/users/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersProfileGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async usersProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersProfileGet200Response> {
        const response = await this.usersProfileGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async usersRegisterRaw(requestParameters: UsersRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersRegister200Response>> {
        if (requestParameters['usersRegisterRequest'] == null) {
            throw new runtime.RequiredError(
                'usersRegisterRequest',
                'Required parameter "usersRegisterRequest" was null or undefined when calling usersRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersRegisterRequestToJSON(requestParameters['usersRegisterRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersRegister200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async usersRegister(requestParameters: UsersRegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersRegister200Response> {
        const response = await this.usersRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
