/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelsCreateRequestAvatarFile } from './ChannelsCreateRequestAvatarFile';
import {
    ChannelsCreateRequestAvatarFileFromJSON,
    ChannelsCreateRequestAvatarFileFromJSONTyped,
    ChannelsCreateRequestAvatarFileToJSON,
} from './ChannelsCreateRequestAvatarFile';
import type { ChannelsCreateRequestTranslations } from './ChannelsCreateRequestTranslations';
import {
    ChannelsCreateRequestTranslationsFromJSON,
    ChannelsCreateRequestTranslationsFromJSONTyped,
    ChannelsCreateRequestTranslationsToJSON,
} from './ChannelsCreateRequestTranslations';

/**
 * 
 * @export
 * @interface ChannelsUpdateRequest
 */
export interface ChannelsUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsUpdateRequest
     */
    description?: string;
    /**
     * 
     * @type {ChannelsCreateRequestAvatarFile}
     * @memberof ChannelsUpdateRequest
     */
    avatarFile: ChannelsCreateRequestAvatarFile;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelsUpdateRequest
     */
    showCollectedSum: boolean;
    /**
     * 
     * @type {ChannelsCreateRequestTranslations}
     * @memberof ChannelsUpdateRequest
     */
    translations?: ChannelsCreateRequestTranslations;
}

/**
 * Check if a given object implements the ChannelsUpdateRequest interface.
 */
export function instanceOfChannelsUpdateRequest(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('title' in value)) return false;
    if (!('avatarFile' in value)) return false;
    if (!('showCollectedSum' in value)) return false;
    return true;
}

export function ChannelsUpdateRequestFromJSON(json: any): ChannelsUpdateRequest {
    return ChannelsUpdateRequestFromJSONTyped(json, false);
}

export function ChannelsUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'avatarFile': ChannelsCreateRequestAvatarFileFromJSON(json['avatar_file']),
        'showCollectedSum': json['show_collected_sum'],
        'translations': json['translations'] == null ? undefined : ChannelsCreateRequestTranslationsFromJSON(json['translations']),
    };
}

export function ChannelsUpdateRequestToJSON(value?: ChannelsUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'avatar_file': ChannelsCreateRequestAvatarFileToJSON(value['avatarFile']),
        'show_collected_sum': value['showCollectedSum'],
        'translations': ChannelsCreateRequestTranslationsToJSON(value['translations']),
    };
}

