/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelsCreateRequestAvatarFile } from './ChannelsCreateRequestAvatarFile';
import {
    ChannelsCreateRequestAvatarFileFromJSON,
    ChannelsCreateRequestAvatarFileFromJSONTyped,
    ChannelsCreateRequestAvatarFileToJSON,
} from './ChannelsCreateRequestAvatarFile';

/**
 * 
 * @export
 * @interface ChannelsCreateRequest
 */
export interface ChannelsCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ChannelsCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsCreateRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsCreateRequest
     */
    description?: string;
    /**
     * 
     * @type {ChannelsCreateRequestAvatarFile}
     * @memberof ChannelsCreateRequest
     */
    avatarFile: ChannelsCreateRequestAvatarFile;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelsCreateRequest
     */
    showCollectedSum: boolean;
}

/**
 * Check if a given object implements the ChannelsCreateRequest interface.
 */
export function instanceOfChannelsCreateRequest(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('title' in value)) return false;
    if (!('avatarFile' in value)) return false;
    if (!('showCollectedSum' in value)) return false;
    return true;
}

export function ChannelsCreateRequestFromJSON(json: any): ChannelsCreateRequest {
    return ChannelsCreateRequestFromJSONTyped(json, false);
}

export function ChannelsCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'avatarFile': ChannelsCreateRequestAvatarFileFromJSON(json['avatar_file']),
        'showCollectedSum': json['show_collected_sum'],
    };
}

export function ChannelsCreateRequestToJSON(value?: ChannelsCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'title': value['title'],
        'description': value['description'],
        'avatar_file': ChannelsCreateRequestAvatarFileToJSON(value['avatarFile']),
        'show_collected_sum': value['showCollectedSum'],
    };
}

