/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicChannel } from './PublicChannel';
import {
    PublicChannelFromJSON,
    PublicChannelFromJSONTyped,
    PublicChannelToJSON,
} from './PublicChannel';

/**
 * 
 * @export
 * @interface ChannelsFeaturedList200Response
 */
export interface ChannelsFeaturedList200Response {
    /**
     * 
     * @type {string}
     * @memberof ChannelsFeaturedList200Response
     */
    status: string;
    /**
     * 
     * @type {Array<PublicChannel>}
     * @memberof ChannelsFeaturedList200Response
     */
    data: Array<PublicChannel>;
    /**
     * 
     * @type {number}
     * @memberof ChannelsFeaturedList200Response
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ChannelsFeaturedList200Response
     */
    total: number;
}

/**
 * Check if a given object implements the ChannelsFeaturedList200Response interface.
 */
export function instanceOfChannelsFeaturedList200Response(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('data' in value)) return false;
    if (!('count' in value)) return false;
    if (!('total' in value)) return false;
    return true;
}

export function ChannelsFeaturedList200ResponseFromJSON(json: any): ChannelsFeaturedList200Response {
    return ChannelsFeaturedList200ResponseFromJSONTyped(json, false);
}

export function ChannelsFeaturedList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsFeaturedList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': ((json['data'] as Array<any>).map(PublicChannelFromJSON)),
        'count': json['count'],
        'total': json['total'],
    };
}

export function ChannelsFeaturedList200ResponseToJSON(value?: ChannelsFeaturedList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ((value['data'] as Array<any>).map(PublicChannelToJSON)),
        'count': value['count'],
        'total': value['total'],
    };
}

