/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrivateChannel } from './PrivateChannel';
import {
    PrivateChannelFromJSON,
    PrivateChannelFromJSONTyped,
    PrivateChannelToJSON,
} from './PrivateChannel';

/**
 * 
 * @export
 * @interface ChannelsCreate200Response
 */
export interface ChannelsCreate200Response {
    /**
     * 
     * @type {string}
     * @memberof ChannelsCreate200Response
     */
    status: string;
    /**
     * 
     * @type {PrivateChannel}
     * @memberof ChannelsCreate200Response
     */
    data: PrivateChannel;
}

/**
 * Check if a given object implements the ChannelsCreate200Response interface.
 */
export function instanceOfChannelsCreate200Response(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('data' in value)) return false;
    return true;
}

export function ChannelsCreate200ResponseFromJSON(json: any): ChannelsCreate200Response {
    return ChannelsCreate200ResponseFromJSONTyped(json, false);
}

export function ChannelsCreate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsCreate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': PrivateChannelFromJSON(json['data']),
    };
}

export function ChannelsCreate200ResponseToJSON(value?: ChannelsCreate200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': PrivateChannelToJSON(value['data']),
    };
}

