/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonationsInit200ResponseData
 */
export interface DonationsInit200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof DonationsInit200ResponseData
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof DonationsInit200ResponseData
     */
    data: string;
}

/**
 * Check if a given object implements the DonationsInit200ResponseData interface.
 */
export function instanceOfDonationsInit200ResponseData(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('data' in value)) return false;
    return true;
}

export function DonationsInit200ResponseDataFromJSON(json: any): DonationsInit200ResponseData {
    return DonationsInit200ResponseDataFromJSONTyped(json, false);
}

export function DonationsInit200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationsInit200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'data': json['data'],
    };
}

export function DonationsInit200ResponseDataToJSON(value?: DonationsInit200ResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'data': value['data'],
    };
}

