/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersEmailConfirmationResend200Response } from './UsersEmailConfirmationResend200Response';
import {
    UsersEmailConfirmationResend200ResponseFromJSON,
    UsersEmailConfirmationResend200ResponseFromJSONTyped,
    UsersEmailConfirmationResend200ResponseToJSON,
} from './UsersEmailConfirmationResend200Response';

/**
 * 
 * @export
 * @interface DonationsStatus200Response
 */
export interface DonationsStatus200Response {
    /**
     * 
     * @type {string}
     * @memberof DonationsStatus200Response
     */
    status: string;
    /**
     * 
     * @type {UsersEmailConfirmationResend200Response}
     * @memberof DonationsStatus200Response
     */
    data: UsersEmailConfirmationResend200Response;
}

/**
 * Check if a given object implements the DonationsStatus200Response interface.
 */
export function instanceOfDonationsStatus200Response(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('data' in value)) return false;
    return true;
}

export function DonationsStatus200ResponseFromJSON(json: any): DonationsStatus200Response {
    return DonationsStatus200ResponseFromJSONTyped(json, false);
}

export function DonationsStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationsStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': UsersEmailConfirmationResend200ResponseFromJSON(json['data']),
    };
}

export function DonationsStatus200ResponseToJSON(value?: DonationsStatus200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': UsersEmailConfirmationResend200ResponseToJSON(value['data']),
    };
}

