/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonationsStatusRequest
 */
export interface DonationsStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof DonationsStatusRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DonationsStatusRequest
     */
    email: string;
}

/**
 * Check if a given object implements the DonationsStatusRequest interface.
 */
export function instanceOfDonationsStatusRequest(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('email' in value)) return false;
    return true;
}

export function DonationsStatusRequestFromJSON(json: any): DonationsStatusRequest {
    return DonationsStatusRequestFromJSONTyped(json, false);
}

export function DonationsStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonationsStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
    };
}

export function DonationsStatusRequestToJSON(value?: DonationsStatusRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
    };
}

