/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Geo } from './Geo';
import {
    GeoFromJSON,
    GeoFromJSONTyped,
    GeoToJSON,
} from './Geo';

/**
 * 
 * @export
 * @interface GeoList200Response
 */
export interface GeoList200Response {
    /**
     * 
     * @type {string}
     * @memberof GeoList200Response
     */
    status: string;
    /**
     * 
     * @type {Array<Geo>}
     * @memberof GeoList200Response
     */
    data: Array<Geo>;
}

/**
 * Check if a given object implements the GeoList200Response interface.
 */
export function instanceOfGeoList200Response(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('data' in value)) return false;
    return true;
}

export function GeoList200ResponseFromJSON(json: any): GeoList200Response {
    return GeoList200ResponseFromJSONTyped(json, false);
}

export function GeoList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': ((json['data'] as Array<any>).map(GeoFromJSON)),
    };
}

export function GeoList200ResponseToJSON(value?: GeoList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': ((value['data'] as Array<any>).map(GeoToJSON)),
    };
}

