/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateFile
 */
export interface PrivateFile {
    /**
     * 
     * @type {string}
     * @memberof PrivateFile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateFile
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateFile
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PrivateFile
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof PrivateFile
     */
    externalHref?: string;
}

/**
 * Check if a given object implements the PrivateFile interface.
 */
export function instanceOfPrivateFile(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('size' in value)) return false;
    return true;
}

export function PrivateFileFromJSON(json: any): PrivateFile {
    return PrivateFileFromJSONTyped(json, false);
}

export function PrivateFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateFile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'publicKey': json['public_key'] == null ? undefined : json['public_key'],
        'name': json['name'],
        'size': json['size'],
        'externalHref': json['external_href'] == null ? undefined : json['external_href'],
    };
}

export function PrivateFileToJSON(value?: PrivateFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'public_key': value['publicKey'],
        'name': value['name'],
        'size': value['size'],
        'external_href': value['externalHref'],
    };
}

