/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersRegisterRequest
 */
export interface UsersRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersRegisterRequest
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof UsersRegisterRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UsersRegisterRequest interface.
 */
export function instanceOfUsersRegisterRequest(value: object): boolean {
    if (!('login' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function UsersRegisterRequestFromJSON(json: any): UsersRegisterRequest {
    return UsersRegisterRequestFromJSONTyped(json, false);
}

export function UsersRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
    };
}

export function UsersRegisterRequestToJSON(value?: UsersRegisterRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'login': value['login'],
        'password': value['password'],
    };
}

