/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersProfileUpdateRequestAuth
 */
export interface UsersProfileUpdateRequestAuth {
    /**
     * 
     * @type {string}
     * @memberof UsersProfileUpdateRequestAuth
     */
    currentPassword: string;
    /**
     * 
     * @type {string}
     * @memberof UsersProfileUpdateRequestAuth
     */
    newPassword: string;
}

/**
 * Check if a given object implements the UsersProfileUpdateRequestAuth interface.
 */
export function instanceOfUsersProfileUpdateRequestAuth(value: object): boolean {
    if (!('currentPassword' in value)) return false;
    if (!('newPassword' in value)) return false;
    return true;
}

export function UsersProfileUpdateRequestAuthFromJSON(json: any): UsersProfileUpdateRequestAuth {
    return UsersProfileUpdateRequestAuthFromJSONTyped(json, false);
}

export function UsersProfileUpdateRequestAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileUpdateRequestAuth {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
    };
}

export function UsersProfileUpdateRequestAuthToJSON(value?: UsersProfileUpdateRequestAuth | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
    };
}

