/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersEmailConfirmationResend200Response
 */
export interface UsersEmailConfirmationResend200Response {
    /**
     * 
     * @type {string}
     * @memberof UsersEmailConfirmationResend200Response
     */
    status: string;
}

/**
 * Check if a given object implements the UsersEmailConfirmationResend200Response interface.
 */
export function instanceOfUsersEmailConfirmationResend200Response(value: object): boolean {
    if (!('status' in value)) return false;
    return true;
}

export function UsersEmailConfirmationResend200ResponseFromJSON(json: any): UsersEmailConfirmationResend200Response {
    return UsersEmailConfirmationResend200ResponseFromJSONTyped(json, false);
}

export function UsersEmailConfirmationResend200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersEmailConfirmationResend200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function UsersEmailConfirmationResend200ResponseToJSON(value?: UsersEmailConfirmationResend200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

