/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersRegister200ResponseData } from './UsersRegister200ResponseData';
import {
    UsersRegister200ResponseDataFromJSON,
    UsersRegister200ResponseDataFromJSONTyped,
    UsersRegister200ResponseDataToJSON,
} from './UsersRegister200ResponseData';

/**
 * 
 * @export
 * @interface UsersRegister200Response
 */
export interface UsersRegister200Response {
    /**
     * 
     * @type {string}
     * @memberof UsersRegister200Response
     */
    status: string;
    /**
     * 
     * @type {UsersRegister200ResponseData}
     * @memberof UsersRegister200Response
     */
    data: UsersRegister200ResponseData;
}

/**
 * Check if a given object implements the UsersRegister200Response interface.
 */
export function instanceOfUsersRegister200Response(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('data' in value)) return false;
    return true;
}

export function UsersRegister200ResponseFromJSON(json: any): UsersRegister200Response {
    return UsersRegister200ResponseFromJSONTyped(json, false);
}

export function UsersRegister200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersRegister200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': UsersRegister200ResponseDataFromJSON(json['data']),
    };
}

export function UsersRegister200ResponseToJSON(value?: UsersRegister200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': UsersRegister200ResponseDataToJSON(value['data']),
    };
}

