/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersProfileUpdateRequestAvatar
 */
export interface UsersProfileUpdateRequestAvatar {
    /**
     * 
     * @type {string}
     * @memberof UsersProfileUpdateRequestAvatar
     */
    id: string;
}

/**
 * Check if a given object implements the UsersProfileUpdateRequestAvatar interface.
 */
export function instanceOfUsersProfileUpdateRequestAvatar(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function UsersProfileUpdateRequestAvatarFromJSON(json: any): UsersProfileUpdateRequestAvatar {
    return UsersProfileUpdateRequestAvatarFromJSONTyped(json, false);
}

export function UsersProfileUpdateRequestAvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileUpdateRequestAvatar {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UsersProfileUpdateRequestAvatarToJSON(value?: UsersProfileUpdateRequestAvatar | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

