/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersProfileUpdate200Response
 */
export interface UsersProfileUpdate200Response {
    /**
     * 
     * @type {string}
     * @memberof UsersProfileUpdate200Response
     */
    status: string;
}

/**
 * Check if a given object implements the UsersProfileUpdate200Response interface.
 */
export function instanceOfUsersProfileUpdate200Response(value: object): boolean {
    if (!('status' in value)) return false;
    return true;
}

export function UsersProfileUpdate200ResponseFromJSON(json: any): UsersProfileUpdate200Response {
    return UsersProfileUpdate200ResponseFromJSONTyped(json, false);
}

export function UsersProfileUpdate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileUpdate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function UsersProfileUpdate200ResponseToJSON(value?: UsersProfileUpdate200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
    };
}

