/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersEmailPasswordResetUpdateRequest
 */
export interface UsersEmailPasswordResetUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersEmailPasswordResetUpdateRequest
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof UsersEmailPasswordResetUpdateRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the UsersEmailPasswordResetUpdateRequest interface.
 */
export function instanceOfUsersEmailPasswordResetUpdateRequest(value: object): boolean {
    if (!('token' in value)) return false;
    if (!('newPassword' in value)) return false;
    return true;
}

export function UsersEmailPasswordResetUpdateRequestFromJSON(json: any): UsersEmailPasswordResetUpdateRequest {
    return UsersEmailPasswordResetUpdateRequestFromJSONTyped(json, false);
}

export function UsersEmailPasswordResetUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersEmailPasswordResetUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'newPassword': json['new_password'],
    };
}

export function UsersEmailPasswordResetUpdateRequestToJSON(value?: UsersEmailPasswordResetUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
        'new_password': value['newPassword'],
    };
}

