/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersLoginRequest
 */
export interface UsersLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersLoginRequest
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof UsersLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the UsersLoginRequest interface.
 */
export function instanceOfUsersLoginRequest(value: object): boolean {
    if (!('login' in value)) return false;
    if (!('password' in value)) return false;
    return true;
}

export function UsersLoginRequestFromJSON(json: any): UsersLoginRequest {
    return UsersLoginRequestFromJSONTyped(json, false);
}

export function UsersLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
    };
}

export function UsersLoginRequestToJSON(value?: UsersLoginRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'login': value['login'],
        'password': value['password'],
    };
}

