/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UsersProfileGet200Response
 */
export interface UsersProfileGet200Response {
    /**
     * 
     * @type {string}
     * @memberof UsersProfileGet200Response
     */
    status: string;
    /**
     * 
     * @type {User}
     * @memberof UsersProfileGet200Response
     */
    data: User;
}

/**
 * Check if a given object implements the UsersProfileGet200Response interface.
 */
export function instanceOfUsersProfileGet200Response(value: object): boolean {
    if (!('status' in value)) return false;
    if (!('data' in value)) return false;
    return true;
}

export function UsersProfileGet200ResponseFromJSON(json: any): UsersProfileGet200Response {
    return UsersProfileGet200ResponseFromJSONTyped(json, false);
}

export function UsersProfileGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': UserFromJSON(json['data']),
    };
}

export function UsersProfileGet200ResponseToJSON(value?: UsersProfileGet200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'data': UserToJSON(value['data']),
    };
}

