/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersProfileUpdateRequestAuth } from './UsersProfileUpdateRequestAuth';
import {
    UsersProfileUpdateRequestAuthFromJSON,
    UsersProfileUpdateRequestAuthFromJSONTyped,
    UsersProfileUpdateRequestAuthToJSON,
} from './UsersProfileUpdateRequestAuth';
import type { UsersProfileUpdateRequestAvatar } from './UsersProfileUpdateRequestAvatar';
import {
    UsersProfileUpdateRequestAvatarFromJSON,
    UsersProfileUpdateRequestAvatarFromJSONTyped,
    UsersProfileUpdateRequestAvatarToJSON,
} from './UsersProfileUpdateRequestAvatar';

/**
 * 
 * @export
 * @interface UsersProfileUpdateRequest
 */
export interface UsersProfileUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersProfileUpdateRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersProfileUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {UsersProfileUpdateRequestAuth}
     * @memberof UsersProfileUpdateRequest
     */
    auth?: UsersProfileUpdateRequestAuth;
    /**
     * 
     * @type {UsersProfileUpdateRequestAvatar}
     * @memberof UsersProfileUpdateRequest
     */
    avatar?: UsersProfileUpdateRequestAvatar;
}

/**
 * Check if a given object implements the UsersProfileUpdateRequest interface.
 */
export function instanceOfUsersProfileUpdateRequest(value: object): boolean {
    return true;
}

export function UsersProfileUpdateRequestFromJSON(json: any): UsersProfileUpdateRequest {
    return UsersProfileUpdateRequestFromJSONTyped(json, false);
}

export function UsersProfileUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersProfileUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'auth': json['auth'] == null ? undefined : UsersProfileUpdateRequestAuthFromJSON(json['auth']),
        'avatar': json['avatar'] == null ? undefined : UsersProfileUpdateRequestAvatarFromJSON(json['avatar']),
    };
}

export function UsersProfileUpdateRequestToJSON(value?: UsersProfileUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
        'auth': UsersProfileUpdateRequestAuthToJSON(value['auth']),
        'avatar': UsersProfileUpdateRequestAvatarToJSON(value['avatar']),
    };
}

