/* tslint:disable */
/* eslint-disable */
/**
 * Nextube Donations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersEmailPasswordResetRequest
 */
export interface UsersEmailPasswordResetRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersEmailPasswordResetRequest
     */
    email: string;
}

/**
 * Check if a given object implements the UsersEmailPasswordResetRequest interface.
 */
export function instanceOfUsersEmailPasswordResetRequest(value: object): boolean {
    if (!('email' in value)) return false;
    return true;
}

export function UsersEmailPasswordResetRequestFromJSON(json: any): UsersEmailPasswordResetRequest {
    return UsersEmailPasswordResetRequestFromJSONTyped(json, false);
}

export function UsersEmailPasswordResetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersEmailPasswordResetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function UsersEmailPasswordResetRequestToJSON(value?: UsersEmailPasswordResetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

